[tool.poetry]
name = "klepp"
version = "0.1.0"
description = "API for uploading/deleting S3 files"
authors = [
    "Jonas Krüger Svensson <jonas-ks@hotmail.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.63.0"
uvicorn = {extras = ["standard"], version = "^0.13.4"}
python-decouple = "^3.4"
python-multipart = "^0.0.5"
aioboto3 = "^8.3.0"
aioaws = "^0.8"
pip = "^21.1.1"
install = "^1.3.4"
tortoise-orm = {extras = ["asyncpg"], version = "^0.17.2"}
asyncpg = "^0.22.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.9.3"
black = "^20.8b1"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-asyncio = "^0.14.0"
pytest-mock = "^3.5.1"
isort = "^5.8.0"

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
    (\.eggs|\.git|\.hg|\.mypy_cache|\.tox|\.venv|\venv|\.github|\docs|\tests|\__pycache__)
)
'''

[tool.isort]
profile = "black"
src_paths = ["app"]
combine_as_imports = true
line_length = 120
sections = [
    'FUTURE',
    'STDLIB',
    'THIRDPARTY',
    'FIRSTPARTY',
    'LOCALFOLDER'
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
